### ISSUE TITLE
Tell the user which proto files we're reading from

### ISSUE THREAD

**Issue by bjohnson-va** [bjohnson-va/pmcli#7]
Users might expect that we're using the protofiles from the associated project (e.g. from within advertising).  But we actually default to vendastaapis on $GOPATH.

We should dump this info into the console when they run pmcli.

**Comment by jguenther-va** [comment]
I believe it's possible to figure out "where would this package be imported from?" with some sort of golang CLI tool... I'll have to go look, but I'm pretty sure that's possible

if so, it'd also be nice if pmcli would grab proto's from the project's vendor folder directly, rather than from vendastaapis in your GOPATH

If anyone starts on this feel free to ping me and I'll try to find what I'm thinking of there...

**Comment by bjohnson-va** [comment]
PMCLI now honors the `PMCLI_ROOT` environment variable.  A sane default for this would be your checked-out version of vendastaapis.  E.g. `/home/bjohnson-va/projects/vendastaapis`
